name: Compile

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['0.1.3']
        arch: ['amd64']

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build ./docker --tag builder:local
    - name: Compile
      run: |
        mkdir -p out dl
        docker run --rm \
           -v $(pwd)/out:/out \
           -v $(pwd)/dl:/dl \
           builder:local \
           /out/xarexec-static.tgz
        ls -lh ./out
        tar tzvf ./out/xarexec-static.tgz
    - name: Make Debian Package
      run: |
        ./pkg_debian.sh $version $arch
        dpkg --info "xarexec-static_${version}_${arch}.deb"
      env:
        version: ${{ matrix.version }}
        arch: ${{ matrix.arch }}

    - name: Upload Artifacts (tgz)
      uses: actions/upload-artifact@v1
      with:
          name: xarexec-static.tgz
          path: out/xarexec-static.tgz

    - name: Upload Artifacts (deb)
      uses: actions/upload-artifact@v1
      with:
          name: xarexec-static_${{ matrix.version }}_${{ matrix.arch }}.deb
          path: xarexec-static_${{ matrix.version }}_${{ matrix.arch }}.deb

    - name: Upload release asset (tgz)
      uses: actions/upload-release-asset@v1.0.1
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./out/xarexec-static.tgz
        asset_name: xarexec-static.tgz
        asset_content_type: application/gzip

    - name: Upload release asset (deb)
      uses: actions/upload-release-asset@v1.0.1
      if: github.event.action == 'published'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: xarexec-static_${{ matrix.version }}_${{ matrix.arch }}.deb
        asset_name: xarexec-static_${{ matrix.version }}_${{ matrix.arch }}.deb
        asset_content_type: application/vnd.debian.binary-package
